/*
 * DO NOT EDIT. This file is auto generated by the Solaris Audit
 * system from adt.xml.
 *
 * See http://opensolaris.org/os/project/audit/
 */

#include <bsm/libbsm.h>
#include <adt_xlate.h>
#include <libintl.h>

#ifndef _PRAUDIT
/* Internal data type definitions */

static datadef	adr0[1] =	{{ADT_MSG, ADT_LIST_LOGIN_TEXT}};
static datadef	adr1[1] =	{{ADT_CHARSTAR, sizeof (char *)}};
static datadef	adr2[2] =	{{ADT_UID, sizeof (uid_t)},
				{ADT_CHARSTAR, sizeof (char *)}};
static datadef	adr3[3] =	{{ADT_INT, sizeof (int)},
				{ADT_CHAR2STAR, sizeof (char **)},
				{ADT_CHAR2STAR, sizeof (char **)}};
static datadef	adr4[8] =	{{ADT_UID, sizeof (uid_t)},
				{ADT_UID, sizeof (uid_t)},
				{ADT_GID, sizeof (gid_t)},
				{ADT_UID, sizeof (uid_t)},
				{ADT_GID, sizeof (gid_t)},
				{ADT_PID, sizeof (pid_t)},
				{ADT_UINT32, sizeof (au_asid_t)},
				{ADT_TERMIDSTAR, sizeof (au_tid_addr_t *)}};
static datadef	adr5[1] =	{{ADT_PRIVSTAR, sizeof (priv_set_t *)}};
static datadef	adr6[4] =	{{ADT_UINT32, sizeof (uint32_t)},
				{ADT_UINT16, sizeof (uint16_t)},
				{ADT_UINT16, sizeof (uint16_t)},
				{ADT_UINT32ARRAY, 4 * sizeof (uint32_t)}};
static datadef	adr7[1] =	{{ADT_MLABELSTAR, sizeof (m_label_t *)}};
static datadef	adr8[1] =	{{ADT_MSG, ADT_LIST_UADMIN_FCN}};
static datadef	adr9[2] =	{{ADT_CHAR2STAR, sizeof (char **)},
				{ADT_INT, sizeof (int)}};
static datadef	adr10[1] =	{{ADT_FD, sizeof (fd_t)}};
static datadef	adr11[1] =	{{ADT_INT, sizeof (int)}};
static datadef	adr12[1] =	{{ADT_MSG, ADT_LIST_TPM_E}};
static datadef	adr13[1] =	{{ADT_INT32, sizeof (int32_t)}};
static datadef	adr14[2] =	{{ADT_INT32, sizeof (int32_t)},
				{ADT_UINT32ARRAY, 4 * sizeof (uint32_t)}};
static datadef	adr15[1] =	{{ADT_UINT16, sizeof (uint16_t)}};
static datadef	adr16[1] =	{{ADT_UINT32, sizeof (uint32_t)}};

/* External event structure to internal event structure */

static struct entry XX_admin_authenticate[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_admin_authenticate[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr0[0],	&(XX_admin_authenticate[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_admin_authenticate = {
	0,
	ADT_admin_authenticate,
	AUE_admin_authenticate,
	3,
	&XX_admin_authenticate[0],
	&XX_admin_authenticate[0]
};
static struct entry XX_attach[6] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_attach[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_attach[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_attach[3]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_attach[4]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_attach[5]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_attach = {
	0,
	ADT_attach,
	AUE_attach,
	6,
	&XX_attach[0],
	&XX_attach[0]
};
static struct entry XX_cpu_ondemand[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_cpu_ondemand[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_cpu_ondemand[2]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_cpu_ondemand = {
	0,
	ADT_cpu_ondemand,
	AUE_cpu_ondemand,
	3,
	&XX_cpu_ondemand[0],
	&XX_cpu_ondemand[0]
};
static struct entry XX_cpu_performance[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_cpu_performance[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_cpu_performance[2]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_cpu_performance = {
	0,
	ADT_cpu_performance,
	AUE_cpu_performance,
	3,
	&XX_cpu_performance[0],
	&XX_cpu_performance[0]
};
static struct entry XX_cpu_threshold[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_cpu_threshold[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_cpu_threshold[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr11[0],	&(XX_cpu_threshold[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_cpu_threshold = {
	0,
	ADT_cpu_threshold,
	AUE_cpu_threshold,
	4,
	&XX_cpu_threshold[0],
	&XX_cpu_threshold[0]
};
static struct entry XX_detach[6] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_detach[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_detach[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_detach[3]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_detach[4]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_detach[5]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_detach = {
	0,
	ADT_detach,
	AUE_detach,
	6,
	&XX_detach[0],
	&XX_detach[0]
};
static struct entry XX_dladm_create_secobj[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_dladm_create_secobj[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_dladm_create_secobj[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_dladm_create_secobj[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_dladm_create_secobj[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_dladm_create_secobj = {
	0,
	ADT_dladm_create_secobj,
	AUE_dladm_create_secobj,
	5,
	&XX_dladm_create_secobj[0],
	&XX_dladm_create_secobj[0]
};
static struct entry XX_dladm_delete_secobj[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_dladm_delete_secobj[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_dladm_delete_secobj[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_dladm_delete_secobj[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_dladm_delete_secobj[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_dladm_delete_secobj = {
	0,
	ADT_dladm_delete_secobj,
	AUE_dladm_delete_secobj,
	5,
	&XX_dladm_delete_secobj[0],
	&XX_dladm_delete_secobj[0]
};
static struct entry XX_file_copy[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_file_copy[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_file_copy[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_file_copy[3]),
		0,	1,	0,	NULL},
	{AUT_LABEL,	1,	&adr7[0],	&(XX_file_copy[4]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_file_copy[5]),
		0,	1,	0,	NULL},
	{AUT_LABEL,	1,	&adr7[0],	&(XX_file_copy[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_file_copy = {
	0,
	ADT_file_copy,
	AUE_file_copy,
	7,
	&XX_file_copy[0],
	&XX_file_copy[0]
};
static struct entry XX_file_relabel[6] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_file_relabel[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_file_relabel[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_file_relabel[3]),
		0,	1,	0,	NULL},
	{AUT_LABEL,	1,	&adr7[0],	&(XX_file_relabel[4]),
		0,	1,	0,	NULL},
	{AUT_LABEL,	1,	&adr7[0],	&(XX_file_relabel[5]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_file_relabel = {
	0,
	ADT_file_relabel,
	AUE_file_relabel,
	6,
	&XX_file_relabel[0],
	&XX_file_relabel[0]
};
static struct entry XX_filesystem_add[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_filesystem_add[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_add[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_add[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_add[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_filesystem_add[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_add[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_filesystem_add = {
	0,
	ADT_filesystem_add,
	AUE_filesystem_add,
	7,
	&XX_filesystem_add[0],
	&XX_filesystem_add[0]
};
static struct entry XX_filesystem_delete[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_filesystem_delete[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_delete[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_delete[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_delete[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_filesystem_delete[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_delete[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_filesystem_delete = {
	0,
	ADT_filesystem_delete,
	AUE_filesystem_delete,
	7,
	&XX_filesystem_delete[0],
	&XX_filesystem_delete[0]
};
static struct entry XX_filesystem_modify[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_filesystem_modify[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_modify[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_modify[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_modify[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_filesystem_modify[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_filesystem_modify[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_filesystem_modify = {
	0,
	ADT_filesystem_modify,
	AUE_filesystem_modify,
	7,
	&XX_filesystem_modify[0],
	&XX_filesystem_modify[0]
};
static struct entry XX_hotplug_set[6] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_hotplug_set[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_hotplug_set[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_hotplug_set[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_hotplug_set[4]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_hotplug_set[5]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_hotplug_set = {
	0,
	ADT_hotplug_set,
	AUE_hotplug_set,
	6,
	&XX_hotplug_set[0],
	&XX_hotplug_set[0]
};
static struct entry XX_hotplug_state[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_hotplug_state[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_hotplug_state[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_hotplug_state[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_hotplug_state[4]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_hotplug_state[5]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_hotplug_state[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_hotplug_state = {
	0,
	ADT_hotplug_state,
	AUE_hotplug_state,
	7,
	&XX_hotplug_state[0],
	&XX_hotplug_state[0]
};
static struct entry XX_ilb_add_server[8] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_add_server[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_add_server[2]),
		0,	1,	0,	NULL},
	{ADT_IN_REMOTE,	2,	&adr14[0],	&(XX_ilb_add_server[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_add_server[4]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_add_server[5]),
		0,	1,	0,	NULL},
	{AUT_IPORT,	1,	&adr15[0],	&(XX_ilb_add_server[6]),
		0,	0,	0,	NULL},
	{AUT_IPORT,	1,	&adr15[0],	&(XX_ilb_add_server[7]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_add_server = {
	0,
	ADT_ilb_add_server,
	AUE_ilb_add_server,
	8,
	&XX_ilb_add_server[0],
	&XX_ilb_add_server[0]
};
static struct entry XX_ilb_create_healthcheck[8] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_create_healthcheck[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_create_healthcheck[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_ilb_create_healthcheck[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_create_healthcheck[4]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr13[0],	&(XX_ilb_create_healthcheck[5]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr11[0],	&(XX_ilb_create_healthcheck[6]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr13[0],	&(XX_ilb_create_healthcheck[7]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_create_healthcheck = {
	0,
	ADT_ilb_create_healthcheck,
	AUE_ilb_create_healthcheck,
	8,
	&XX_ilb_create_healthcheck[0],
	&XX_ilb_create_healthcheck[0]
};
static struct entry XX_ilb_create_rule[18] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_create_rule[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_create_rule[2]),
		0,	1,	0,	NULL},
	{ADT_IN_REMOTE,	2,	&adr14[0],	&(XX_ilb_create_rule[3]),
		0,	1,	0,	NULL},
	{AUT_IPORT,	1,	&adr15[0],	&(XX_ilb_create_rule[4]),
		0,	1,	0,	NULL},
	{AUT_IPORT,	1,	&adr15[0],	&(XX_ilb_create_rule[5]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_create_rule[6]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_create_rule[7]),
		0,	1,	0,	NULL},
	{ADT_IN_REMOTE,	2,	&adr14[0],	&(XX_ilb_create_rule[8]),
		0,	0,	0,	NULL},
	{ADT_IN_REMOTE,	2,	&adr14[0],	&(XX_ilb_create_rule[9]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_create_rule[10]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_create_rule[11]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_create_rule[12]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr16[0],	&(XX_ilb_create_rule[13]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr16[0],	&(XX_ilb_create_rule[14]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr16[0],	&(XX_ilb_create_rule[15]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_create_rule[16]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_create_rule[17]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_create_rule = {
	0,
	ADT_ilb_create_rule,
	AUE_ilb_create_rule,
	18,
	&XX_ilb_create_rule[0],
	&XX_ilb_create_rule[0]
};
static struct entry XX_ilb_create_servergroup[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_create_servergroup[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_create_servergroup[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_create_servergroup[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_create_servergroup = {
	0,
	ADT_ilb_create_servergroup,
	AUE_ilb_create_servergroup,
	4,
	&XX_ilb_create_servergroup[0],
	&XX_ilb_create_servergroup[0]
};
static struct entry XX_ilb_delete_healthcheck[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_delete_healthcheck[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_delete_healthcheck[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_delete_healthcheck[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_delete_healthcheck = {
	0,
	ADT_ilb_delete_healthcheck,
	AUE_ilb_delete_healthcheck,
	4,
	&XX_ilb_delete_healthcheck[0],
	&XX_ilb_delete_healthcheck[0]
};
static struct entry XX_ilb_delete_rule[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_delete_rule[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_delete_rule[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_delete_rule[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_delete_rule = {
	0,
	ADT_ilb_delete_rule,
	AUE_ilb_delete_rule,
	4,
	&XX_ilb_delete_rule[0],
	&XX_ilb_delete_rule[0]
};
static struct entry XX_ilb_delete_servergroup[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_delete_servergroup[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_delete_servergroup[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_delete_servergroup[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_delete_servergroup = {
	0,
	ADT_ilb_delete_servergroup,
	AUE_ilb_delete_servergroup,
	4,
	&XX_ilb_delete_servergroup[0],
	&XX_ilb_delete_servergroup[0]
};
static struct entry XX_ilb_disable_rule[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_disable_rule[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_disable_rule[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_disable_rule[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_disable_rule = {
	0,
	ADT_ilb_disable_rule,
	AUE_ilb_disable_rule,
	4,
	&XX_ilb_disable_rule[0],
	&XX_ilb_disable_rule[0]
};
static struct entry XX_ilb_disable_server[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_disable_server[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_disable_server[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_disable_server[3]),
		0,	1,	0,	NULL},
	{ADT_IN_REMOTE,	2,	&adr14[0],	&(XX_ilb_disable_server[4]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_disable_server = {
	0,
	ADT_ilb_disable_server,
	AUE_ilb_disable_server,
	5,
	&XX_ilb_disable_server[0],
	&XX_ilb_disable_server[0]
};
static struct entry XX_ilb_enable_rule[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_enable_rule[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_enable_rule[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_enable_rule[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_enable_rule = {
	0,
	ADT_ilb_enable_rule,
	AUE_ilb_enable_rule,
	4,
	&XX_ilb_enable_rule[0],
	&XX_ilb_enable_rule[0]
};
static struct entry XX_ilb_enable_server[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_enable_server[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_enable_server[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_enable_server[3]),
		0,	1,	0,	NULL},
	{ADT_IN_REMOTE,	2,	&adr14[0],	&(XX_ilb_enable_server[4]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_enable_server = {
	0,
	ADT_ilb_enable_server,
	AUE_ilb_enable_server,
	5,
	&XX_ilb_enable_server[0],
	&XX_ilb_enable_server[0]
};
static struct entry XX_ilb_remove_server[6] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ilb_remove_server[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_ilb_remove_server[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_remove_server[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_ilb_remove_server[4]),
		0,	1,	0,	NULL},
	{ADT_IN_REMOTE,	2,	&adr14[0],	&(XX_ilb_remove_server[5]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ilb_remove_server = {
	0,
	ADT_ilb_remove_server,
	AUE_ilb_remove_server,
	6,
	&XX_ilb_remove_server[0],
	&XX_ilb_remove_server[0]
};
static struct entry XX_inetd_connect[6] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_inetd_connect[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_inetd_connect[2]),
		0,	0,	0,	NULL},
	{AUT_TID,	4,	&adr6[0],	&(XX_inetd_connect[3]),
		0,	1,	0,	NULL},
	{ADT_CMD_ALT,	1,	&adr1[0],	&(XX_inetd_connect[4]),
		0,	1,	0,	NULL},
	{ADT_AUT_PRIV_E,	1,	&adr5[0],	&(XX_inetd_connect[5]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_inetd_connect = {
	0,
	ADT_inetd_connect,
	AUE_inetd_connect,
	6,
	&XX_inetd_connect[0],
	&XX_inetd_connect[0]
};
static struct entry XX_inetd_copylimit[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_inetd_copylimit[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_inetd_copylimit[2]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_inetd_copylimit[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_inetd_copylimit = {
	0,
	ADT_inetd_copylimit,
	AUE_inetd_copylimit,
	4,
	&XX_inetd_copylimit[0],
	&XX_inetd_copylimit[0]
};
static struct entry XX_inetd_failrate[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_inetd_failrate[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_inetd_failrate[2]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_inetd_failrate[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_inetd_failrate = {
	0,
	ADT_inetd_failrate,
	AUE_inetd_failrate,
	4,
	&XX_inetd_failrate[0],
	&XX_inetd_failrate[0]
};
static struct entry XX_inetd_ratelimit[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_inetd_ratelimit[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_inetd_ratelimit[2]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_inetd_ratelimit[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_inetd_ratelimit = {
	0,
	ADT_inetd_ratelimit,
	AUE_inetd_ratelimit,
	4,
	&XX_inetd_ratelimit[0],
	&XX_inetd_ratelimit[0]
};
static struct entry XX_init_solaris[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_init_solaris[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_init_solaris[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_init_solaris = {
	0,
	ADT_init_solaris,
	AUE_init_solaris,
	3,
	&XX_init_solaris[0],
	&XX_init_solaris[0]
};
static struct entry XX_login[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_login[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr0[0],	&(XX_login[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_login = {
	0,
	ADT_login,
	AUE_login,
	3,
	&XX_login[0],
	&XX_login[0]
};
static struct entry XX_logout[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_logout[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_logout[2]),
		0,	0,	0,	"logout %s"},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_logout = {
	0,
	ADT_logout,
	AUE_logout,
	3,
	&XX_logout[0],
	&XX_logout[0]
};
static struct entry XX_ndmp_backup[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ndmp_backup[1]),
		0,	0,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_ndmp_backup[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_ndmp_backup[3]),
		0,	0,	0,	NULL},
	{ADT_IN_PEER,	1,	&adr10[0],	&(XX_ndmp_backup[4]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ndmp_backup = {
	0,
	ADT_ndmp_backup,
	AUE_ndmp_backup,
	5,
	&XX_ndmp_backup[0],
	&XX_ndmp_backup[0]
};
static struct entry XX_ndmp_connect[2] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ndmp_connect[1]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ndmp_connect = {
	0,
	ADT_ndmp_connect,
	AUE_ndmp_connect,
	2,
	&XX_ndmp_connect[0],
	&XX_ndmp_connect[0]
};
static struct entry XX_ndmp_disconnect[2] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ndmp_disconnect[1]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ndmp_disconnect = {
	0,
	ADT_ndmp_disconnect,
	AUE_ndmp_disconnect,
	2,
	&XX_ndmp_disconnect[0],
	&XX_ndmp_disconnect[0]
};
static struct entry XX_ndmp_restore[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ndmp_restore[1]),
		0,	0,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_ndmp_restore[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_ndmp_restore[3]),
		0,	0,	0,	NULL},
	{ADT_IN_PEER,	1,	&adr10[0],	&(XX_ndmp_restore[4]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ndmp_restore = {
	0,
	ADT_ndmp_restore,
	AUE_ndmp_restore,
	5,
	&XX_ndmp_restore[0],
	&XX_ndmp_restore[0]
};
static struct entry XX_netcfg_remove[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_netcfg_remove[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_netcfg_remove[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_netcfg_remove[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_netcfg_remove = {
	0,
	ADT_netcfg_remove,
	AUE_netcfg_remove,
	4,
	&XX_netcfg_remove[0],
	&XX_netcfg_remove[0]
};
static struct entry XX_netcfg_update[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_netcfg_update[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_netcfg_update[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_netcfg_update[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_netcfg_update = {
	0,
	ADT_netcfg_update,
	AUE_netcfg_update,
	4,
	&XX_netcfg_update[0],
	&XX_netcfg_update[0]
};
static struct entry XX_network_add[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_network_add[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_add[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_add[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_add[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_network_add[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_add[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_network_add = {
	0,
	ADT_network_add,
	AUE_network_add,
	7,
	&XX_network_add[0],
	&XX_network_add[0]
};
static struct entry XX_network_delete[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_network_delete[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_delete[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_delete[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_delete[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_network_delete[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_delete[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_network_delete = {
	0,
	ADT_network_delete,
	AUE_network_delete,
	7,
	&XX_network_delete[0],
	&XX_network_delete[0]
};
static struct entry XX_network_modify[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_network_modify[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_modify[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_modify[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_modify[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_network_modify[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_network_modify[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_network_modify = {
	0,
	ADT_network_modify,
	AUE_network_modify,
	7,
	&XX_network_modify[0],
	&XX_network_modify[0]
};
static struct entry XX_newgrp_login[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_newgrp_login[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_newgrp_login[2]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_newgrp_login = {
	0,
	ADT_newgrp_login,
	AUE_newgrp_login,
	3,
	&XX_newgrp_login[0],
	&XX_newgrp_login[0]
};
static struct entry XX_nwam_disable[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_nwam_disable[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_nwam_disable[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_nwam_disable[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_nwam_disable = {
	0,
	ADT_nwam_disable,
	AUE_nwam_disable,
	4,
	&XX_nwam_disable[0],
	&XX_nwam_disable[0]
};
static struct entry XX_nwam_enable[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_nwam_enable[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_nwam_enable[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_nwam_enable[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_nwam_enable = {
	0,
	ADT_nwam_enable,
	AUE_nwam_enable,
	4,
	&XX_nwam_enable[0],
	&XX_nwam_enable[0]
};
static struct entry XX_passwd[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_passwd[1]),
		0,	0,	0,	NULL},
	{AUT_USER,	2,	&adr2[0],	&(XX_passwd[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_passwd = {
	0,
	ADT_passwd,
	AUE_passwd,
	3,
	&XX_passwd[0],
	&XX_passwd[0]
};
static struct entry XX_pool_export[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_pool_export[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_pool_export[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_pool_export[3]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_pool_export[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_pool_export = {
	0,
	ADT_pool_export,
	AUE_pool_export,
	5,
	&XX_pool_export[0],
	&XX_pool_export[0]
};
static struct entry XX_pool_import[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_pool_import[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_pool_import[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_pool_import[3]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_pool_import[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_pool_import = {
	0,
	ADT_pool_import,
	AUE_pool_import,
	5,
	&XX_pool_import[0],
	&XX_pool_import[0]
};
static struct entry XX_printer_add[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_printer_add[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_add[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_add[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_add[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_printer_add[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_add[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_printer_add = {
	0,
	ADT_printer_add,
	AUE_printer_add,
	7,
	&XX_printer_add[0],
	&XX_printer_add[0]
};
static struct entry XX_printer_delete[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_printer_delete[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_delete[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_delete[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_delete[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_printer_delete[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_delete[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_printer_delete = {
	0,
	ADT_printer_delete,
	AUE_printer_delete,
	7,
	&XX_printer_delete[0],
	&XX_printer_delete[0]
};
static struct entry XX_printer_modify[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_printer_modify[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_modify[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_modify[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_modify[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_printer_modify[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_printer_modify[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_printer_modify = {
	0,
	ADT_printer_modify,
	AUE_printer_modify,
	7,
	&XX_printer_modify[0],
	&XX_printer_modify[0]
};
static struct entry XX_prof_cmd[8] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_prof_cmd[1]),
		0,	0,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_prof_cmd[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_prof_cmd[3]),
		0,	1,	0,	NULL},
	{AUT_CMD,	3,	&adr3[0],	&(XX_prof_cmd[4]),
		0,	1,	0,	NULL},
	{AUT_PROCESS,	8,	&adr4[0],	&(XX_prof_cmd[5]),
		0,	1,	0,	NULL},
	{ADT_AUT_PRIV_L,	1,	&adr5[0],	&(XX_prof_cmd[6]),
		0,	0,	0,	NULL},
	{ADT_AUT_PRIV_I,	1,	&adr5[0],	&(XX_prof_cmd[7]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_prof_cmd = {
	0,
	ADT_prof_cmd,
	AUE_prof_cmd,
	8,
	&XX_prof_cmd[0],
	&XX_prof_cmd[0]
};
static struct entry XX_remove[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_remove[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_remove[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_remove[3]),
		0,	0,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_remove[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_remove = {
	0,
	ADT_remove,
	AUE_remove,
	5,
	&XX_remove[0],
	&XX_remove[0]
};
static struct entry XX_rlogin[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_rlogin[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr0[0],	&(XX_rlogin[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_rlogin = {
	0,
	ADT_rlogin,
	AUE_rlogin,
	3,
	&XX_rlogin[0],
	&XX_rlogin[0]
};
static struct entry XX_role_login[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_role_login[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr0[0],	&(XX_role_login[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_role_login = {
	0,
	ADT_role_login,
	AUE_role_login,
	3,
	&XX_role_login[0],
	&XX_role_login[0]
};
static struct entry XX_role_logout[2] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_role_logout[1]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_role_logout = {
	0,
	ADT_role_logout,
	AUE_role_logout,
	2,
	&XX_role_logout[0],
	&XX_role_logout[0]
};
static struct entry XX_scheduledjob_add[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_scheduledjob_add[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_add[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_add[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_add[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_scheduledjob_add[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_add[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_scheduledjob_add = {
	0,
	ADT_scheduledjob_add,
	AUE_scheduledjob_add,
	7,
	&XX_scheduledjob_add[0],
	&XX_scheduledjob_add[0]
};
static struct entry XX_scheduledjob_delete[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_scheduledjob_delete[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_delete[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_delete[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_delete[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_scheduledjob_delete[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_delete[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_scheduledjob_delete = {
	0,
	ADT_scheduledjob_delete,
	AUE_scheduledjob_delete,
	7,
	&XX_scheduledjob_delete[0],
	&XX_scheduledjob_delete[0]
};
static struct entry XX_scheduledjob_modify[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_scheduledjob_modify[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_modify[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_modify[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_modify[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_scheduledjob_modify[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_scheduledjob_modify[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_scheduledjob_modify = {
	0,
	ADT_scheduledjob_modify,
	AUE_scheduledjob_modify,
	7,
	&XX_scheduledjob_modify[0],
	&XX_scheduledjob_modify[0]
};
static struct entry XX_screenlock[2] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_screenlock[1]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_screenlock = {
	0,
	ADT_screenlock,
	AUE_screenlock,
	2,
	&XX_screenlock[0],
	&XX_screenlock[0]
};
static struct entry XX_screenunlock[2] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_screenunlock[1]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_screenunlock = {
	0,
	ADT_screenunlock,
	AUE_screenunlock,
	2,
	&XX_screenunlock[0],
	&XX_screenunlock[0]
};
static struct entry XX_serialport_add[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_serialport_add[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_add[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_add[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_add[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_serialport_add[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_add[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_serialport_add = {
	0,
	ADT_serialport_add,
	AUE_serialport_add,
	7,
	&XX_serialport_add[0],
	&XX_serialport_add[0]
};
static struct entry XX_serialport_delete[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_serialport_delete[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_delete[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_delete[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_delete[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_serialport_delete[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_delete[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_serialport_delete = {
	0,
	ADT_serialport_delete,
	AUE_serialport_delete,
	7,
	&XX_serialport_delete[0],
	&XX_serialport_delete[0]
};
static struct entry XX_serialport_modify[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_serialport_modify[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_modify[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_modify[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_modify[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_serialport_modify[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_serialport_modify[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_serialport_modify = {
	0,
	ADT_serialport_modify,
	AUE_serialport_modify,
	7,
	&XX_serialport_modify[0],
	&XX_serialport_modify[0]
};
static struct entry XX_smbd_logoff[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smbd_logoff[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smbd_logoff[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smbd_logoff[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smbd_logoff = {
	0,
	ADT_smbd_logoff,
	AUE_smbd_logoff,
	4,
	&XX_smbd_logoff[0],
	&XX_smbd_logoff[0]
};
static struct entry XX_smbd_session[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smbd_session[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smbd_session[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smbd_session[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smbd_session[4]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smbd_session = {
	0,
	ADT_smbd_session,
	AUE_smbd_session,
	5,
	&XX_smbd_session[0],
	&XX_smbd_session[0]
};
static struct entry XX_smf_annotation[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_annotation[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_annotation[2]),
		0,	1,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_smf_annotation[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_annotation = {
	0,
	ADT_smf_annotation,
	AUE_smf_annotation,
	4,
	&XX_smf_annotation[0],
	&XX_smf_annotation[0]
};
static struct entry XX_smf_attach_snap[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_attach_snap[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_attach_snap[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_attach_snap[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_attach_snap[4]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_attach_snap[5]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_attach_snap[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_attach_snap = {
	0,
	ADT_smf_attach_snap,
	AUE_smf_attach_snap,
	7,
	&XX_smf_attach_snap[0],
	&XX_smf_attach_snap[0]
};
static struct entry XX_smf_change_prop[6] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_change_prop[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_change_prop[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_change_prop[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_change_prop[4]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_change_prop[5]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_change_prop = {
	0,
	ADT_smf_change_prop,
	AUE_smf_change_prop,
	6,
	&XX_smf_change_prop[0],
	&XX_smf_change_prop[0]
};
static struct entry XX_smf_clear[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_clear[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_clear[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_clear[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_clear = {
	0,
	ADT_smf_clear,
	AUE_smf_clear,
	4,
	&XX_smf_clear[0],
	&XX_smf_clear[0]
};
static struct entry XX_smf_create[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_create[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_create[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_create[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_create = {
	0,
	ADT_smf_create,
	AUE_smf_create,
	4,
	&XX_smf_create[0],
	&XX_smf_create[0]
};
static struct entry XX_smf_create_npg[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_create_npg[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_create_npg[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_create_npg[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_create_npg[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_create_npg = {
	0,
	ADT_smf_create_npg,
	AUE_smf_create_npg,
	5,
	&XX_smf_create_npg[0],
	&XX_smf_create_npg[0]
};
static struct entry XX_smf_create_pg[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_create_pg[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_create_pg[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_create_pg[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_create_pg[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_create_pg = {
	0,
	ADT_smf_create_pg,
	AUE_smf_create_pg,
	5,
	&XX_smf_create_pg[0],
	&XX_smf_create_pg[0]
};
static struct entry XX_smf_create_prop[6] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_create_prop[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_create_prop[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_create_prop[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_create_prop[4]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_create_prop[5]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_create_prop = {
	0,
	ADT_smf_create_prop,
	AUE_smf_create_prop,
	6,
	&XX_smf_create_prop[0],
	&XX_smf_create_prop[0]
};
static struct entry XX_smf_create_snap[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_create_snap[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_create_snap[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_create_snap[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_create_snap[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_create_snap = {
	0,
	ADT_smf_create_snap,
	AUE_smf_create_snap,
	5,
	&XX_smf_create_snap[0],
	&XX_smf_create_snap[0]
};
static struct entry XX_smf_degrade[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_degrade[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_degrade[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_degrade[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_degrade = {
	0,
	ADT_smf_degrade,
	AUE_smf_degrade,
	4,
	&XX_smf_degrade[0],
	&XX_smf_degrade[0]
};
static struct entry XX_smf_delete[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_delete[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_delete[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_delete[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_delete = {
	0,
	ADT_smf_delete,
	AUE_smf_delete,
	4,
	&XX_smf_delete[0],
	&XX_smf_delete[0]
};
static struct entry XX_smf_delete_npg[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_delete_npg[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_delete_npg[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_delete_npg[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_delete_npg[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_delete_npg = {
	0,
	ADT_smf_delete_npg,
	AUE_smf_delete_npg,
	5,
	&XX_smf_delete_npg[0],
	&XX_smf_delete_npg[0]
};
static struct entry XX_smf_delete_pg[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_delete_pg[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_delete_pg[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_delete_pg[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_delete_pg[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_delete_pg = {
	0,
	ADT_smf_delete_pg,
	AUE_smf_delete_pg,
	5,
	&XX_smf_delete_pg[0],
	&XX_smf_delete_pg[0]
};
static struct entry XX_smf_delete_prop[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_delete_prop[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_delete_prop[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_delete_prop[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_delete_prop = {
	0,
	ADT_smf_delete_prop,
	AUE_smf_delete_prop,
	4,
	&XX_smf_delete_prop[0],
	&XX_smf_delete_prop[0]
};
static struct entry XX_smf_delete_snap[5] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_delete_snap[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_delete_snap[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_delete_snap[3]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_smf_delete_snap[4]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_delete_snap = {
	0,
	ADT_smf_delete_snap,
	AUE_smf_delete_snap,
	5,
	&XX_smf_delete_snap[0],
	&XX_smf_delete_snap[0]
};
static struct entry XX_smf_disable[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_disable[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_disable[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_disable[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_disable = {
	0,
	ADT_smf_disable,
	AUE_smf_disable,
	4,
	&XX_smf_disable[0],
	&XX_smf_disable[0]
};
static struct entry XX_smf_enable[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_enable[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_enable[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_enable[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_enable = {
	0,
	ADT_smf_enable,
	AUE_smf_enable,
	4,
	&XX_smf_enable[0],
	&XX_smf_enable[0]
};
static struct entry XX_smf_immediate_degrade[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_immediate_degrade[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_immediate_degrade[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_immediate_degrade[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_immediate_degrade = {
	0,
	ADT_smf_immediate_degrade,
	AUE_smf_immediate_degrade,
	4,
	&XX_smf_immediate_degrade[0],
	&XX_smf_immediate_degrade[0]
};
static struct entry XX_smf_immediate_maintenance[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_immediate_maintenance[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_immediate_maintenance[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_immediate_maintenance[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_immediate_maintenance = {
	0,
	ADT_smf_immediate_maintenance,
	AUE_smf_immediate_maintenance,
	4,
	&XX_smf_immediate_maintenance[0],
	&XX_smf_immediate_maintenance[0]
};
static struct entry XX_smf_immtmp_maintenance[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_immtmp_maintenance[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_immtmp_maintenance[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_immtmp_maintenance[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_immtmp_maintenance = {
	0,
	ADT_smf_immtmp_maintenance,
	AUE_smf_immtmp_maintenance,
	4,
	&XX_smf_immtmp_maintenance[0],
	&XX_smf_immtmp_maintenance[0]
};
static struct entry XX_smf_maintenance[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_maintenance[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_maintenance[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_maintenance[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_maintenance = {
	0,
	ADT_smf_maintenance,
	AUE_smf_maintenance,
	4,
	&XX_smf_maintenance[0],
	&XX_smf_maintenance[0]
};
static struct entry XX_smf_milestone[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_milestone[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_milestone[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_milestone[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_milestone = {
	0,
	ADT_smf_milestone,
	AUE_smf_milestone,
	4,
	&XX_smf_milestone[0],
	&XX_smf_milestone[0]
};
static struct entry XX_smf_read_prop[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_read_prop[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_read_prop[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_read_prop[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_read_prop = {
	0,
	ADT_smf_read_prop,
	AUE_smf_read_prop,
	4,
	&XX_smf_read_prop[0],
	&XX_smf_read_prop[0]
};
static struct entry XX_smf_refresh[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_refresh[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_refresh[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_refresh[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_refresh = {
	0,
	ADT_smf_refresh,
	AUE_smf_refresh,
	4,
	&XX_smf_refresh[0],
	&XX_smf_refresh[0]
};
static struct entry XX_smf_restart[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_restart[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_restart[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_restart[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_restart = {
	0,
	ADT_smf_restart,
	AUE_smf_restart,
	4,
	&XX_smf_restart[0],
	&XX_smf_restart[0]
};
static struct entry XX_smf_tmp_disable[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_tmp_disable[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_tmp_disable[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_tmp_disable[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_tmp_disable = {
	0,
	ADT_smf_tmp_disable,
	AUE_smf_tmp_disable,
	4,
	&XX_smf_tmp_disable[0],
	&XX_smf_tmp_disable[0]
};
static struct entry XX_smf_tmp_enable[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_tmp_enable[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_tmp_enable[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_tmp_enable[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_tmp_enable = {
	0,
	ADT_smf_tmp_enable,
	AUE_smf_tmp_enable,
	4,
	&XX_smf_tmp_enable[0],
	&XX_smf_tmp_enable[0]
};
static struct entry XX_smf_tmp_maintenance[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_smf_tmp_maintenance[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_smf_tmp_maintenance[2]),
		0,	1,	0,	NULL},
	{AUT_FMRI,	1,	&adr1[0],	&(XX_smf_tmp_maintenance[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_smf_tmp_maintenance = {
	0,
	ADT_smf_tmp_maintenance,
	AUE_smf_tmp_maintenance,
	4,
	&XX_smf_tmp_maintenance[0],
	&XX_smf_tmp_maintenance[0]
};
static struct entry XX_ssh[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_ssh[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr0[0],	&(XX_ssh[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_ssh = {
	0,
	ADT_ssh,
	AUE_ssh,
	3,
	&XX_ssh[0],
	&XX_ssh[0]
};
static struct entry XX_su[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_su[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_su[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_su = {
	0,
	ADT_su,
	AUE_su,
	3,
	&XX_su[0],
	&XX_su[0]
};
static struct entry XX_su_logout[2] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_su_logout[1]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_su_logout = {
	0,
	ADT_su_logout,
	AUE_su_logout,
	2,
	&XX_su_logout[0],
	&XX_su_logout[0]
};
static struct entry XX_telnet[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_telnet[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr0[0],	&(XX_telnet[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_telnet = {
	0,
	ADT_telnet,
	AUE_telnet,
	3,
	&XX_telnet[0],
	&XX_telnet[0]
};
static struct entry XX_tpm_certifyselftest[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_certifyselftest[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_certifyselftest[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_certifyselftest = {
	0,
	ADT_tpm_certifyselftest,
	AUE_tpm_certifyselftest,
	3,
	&XX_tpm_certifyselftest[0],
	&XX_tpm_certifyselftest[0]
};
static struct entry XX_tpm_continueselftest[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_continueselftest[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_continueselftest[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_continueselftest = {
	0,
	ADT_tpm_continueselftest,
	AUE_tpm_continueselftest,
	3,
	&XX_tpm_continueselftest[0],
	&XX_tpm_continueselftest[0]
};
static struct entry XX_tpm_disableforceclear[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_disableforceclear[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_disableforceclear[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_disableforceclear = {
	0,
	ADT_tpm_disableforceclear,
	AUE_tpm_disableforceclear,
	3,
	&XX_tpm_disableforceclear[0],
	&XX_tpm_disableforceclear[0]
};
static struct entry XX_tpm_disableownerclear[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_disableownerclear[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_disableownerclear[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_disableownerclear = {
	0,
	ADT_tpm_disableownerclear,
	AUE_tpm_disableownerclear,
	3,
	&XX_tpm_disableownerclear[0],
	&XX_tpm_disableownerclear[0]
};
static struct entry XX_tpm_fieldupgrade[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_fieldupgrade[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_fieldupgrade[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_fieldupgrade = {
	0,
	ADT_tpm_fieldupgrade,
	AUE_tpm_fieldupgrade,
	3,
	&XX_tpm_fieldupgrade[0],
	&XX_tpm_fieldupgrade[0]
};
static struct entry XX_tpm_forceclear[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_forceclear[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_forceclear[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_forceclear = {
	0,
	ADT_tpm_forceclear,
	AUE_tpm_forceclear,
	3,
	&XX_tpm_forceclear[0],
	&XX_tpm_forceclear[0]
};
static struct entry XX_tpm_ownerclear[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_ownerclear[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_ownerclear[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_ownerclear = {
	0,
	ADT_tpm_ownerclear,
	AUE_tpm_ownerclear,
	3,
	&XX_tpm_ownerclear[0],
	&XX_tpm_ownerclear[0]
};
static struct entry XX_tpm_ownersetdisable[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_ownersetdisable[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_ownersetdisable[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_ownersetdisable = {
	0,
	ADT_tpm_ownersetdisable,
	AUE_tpm_ownersetdisable,
	3,
	&XX_tpm_ownersetdisable[0],
	&XX_tpm_ownersetdisable[0]
};
static struct entry XX_tpm_physicaldeactivate[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_physicaldeactivate[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_physicaldeactivate[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_physicaldeactivate = {
	0,
	ADT_tpm_physicaldeactivate,
	AUE_tpm_physicaldeactivate,
	3,
	&XX_tpm_physicaldeactivate[0],
	&XX_tpm_physicaldeactivate[0]
};
static struct entry XX_tpm_physicaldisable[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_physicaldisable[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_physicaldisable[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_physicaldisable = {
	0,
	ADT_tpm_physicaldisable,
	AUE_tpm_physicaldisable,
	3,
	&XX_tpm_physicaldisable[0],
	&XX_tpm_physicaldisable[0]
};
static struct entry XX_tpm_physicalenable[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_physicalenable[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_physicalenable[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_physicalenable = {
	0,
	ADT_tpm_physicalenable,
	AUE_tpm_physicalenable,
	3,
	&XX_tpm_physicalenable[0],
	&XX_tpm_physicalenable[0]
};
static struct entry XX_tpm_physicalpresence[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_physicalpresence[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_physicalpresence[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_physicalpresence = {
	0,
	ADT_tpm_physicalpresence,
	AUE_tpm_physicalpresence,
	3,
	&XX_tpm_physicalpresence[0],
	&XX_tpm_physicalpresence[0]
};
static struct entry XX_tpm_resetlockvalue[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_resetlockvalue[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_resetlockvalue[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_resetlockvalue = {
	0,
	ADT_tpm_resetlockvalue,
	AUE_tpm_resetlockvalue,
	3,
	&XX_tpm_resetlockvalue[0],
	&XX_tpm_resetlockvalue[0]
};
static struct entry XX_tpm_selftestfull[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_selftestfull[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_selftestfull[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_selftestfull = {
	0,
	ADT_tpm_selftestfull,
	AUE_tpm_selftestfull,
	3,
	&XX_tpm_selftestfull[0],
	&XX_tpm_selftestfull[0]
};
static struct entry XX_tpm_setoperatorauth[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_setoperatorauth[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_setoperatorauth[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_setoperatorauth = {
	0,
	ADT_tpm_setoperatorauth,
	AUE_tpm_setoperatorauth,
	3,
	&XX_tpm_setoperatorauth[0],
	&XX_tpm_setoperatorauth[0]
};
static struct entry XX_tpm_setownerinstall[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_setownerinstall[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_setownerinstall[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_setownerinstall = {
	0,
	ADT_tpm_setownerinstall,
	AUE_tpm_setownerinstall,
	3,
	&XX_tpm_setownerinstall[0],
	&XX_tpm_setownerinstall[0]
};
static struct entry XX_tpm_settempdeactivated[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_settempdeactivated[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_settempdeactivated[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_settempdeactivated = {
	0,
	ADT_tpm_settempdeactivated,
	AUE_tpm_settempdeactivated,
	3,
	&XX_tpm_settempdeactivated[0],
	&XX_tpm_settempdeactivated[0]
};
static struct entry XX_tpm_takeownership[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_tpm_takeownership[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr12[0],	&(XX_tpm_takeownership[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_tpm_takeownership = {
	0,
	ADT_tpm_takeownership,
	AUE_tpm_takeownership,
	3,
	&XX_tpm_takeownership[0],
	&XX_tpm_takeownership[0]
};
static struct entry XX_uadmin_config[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_uadmin_config[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr8[0],	&(XX_uadmin_config[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_uadmin_config[3]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_uadmin_config = {
	0,
	ADT_uadmin_config,
	AUE_uadmin_config,
	4,
	&XX_uadmin_config[0],
	&XX_uadmin_config[0]
};
static struct entry XX_uadmin_dump[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_uadmin_dump[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr8[0],	&(XX_uadmin_dump[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_uadmin_dump[3]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_uadmin_dump = {
	0,
	ADT_uadmin_dump,
	AUE_uadmin_dump,
	4,
	&XX_uadmin_dump[0],
	&XX_uadmin_dump[0]
};
static struct entry XX_uadmin_freeze[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_uadmin_freeze[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr8[0],	&(XX_uadmin_freeze[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_uadmin_freeze[3]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_uadmin_freeze = {
	0,
	ADT_uadmin_freeze,
	AUE_uadmin_freeze,
	4,
	&XX_uadmin_freeze[0],
	&XX_uadmin_freeze[0]
};
static struct entry XX_uadmin_ftrace[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_uadmin_ftrace[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr8[0],	&(XX_uadmin_ftrace[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_uadmin_ftrace[3]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_uadmin_ftrace = {
	0,
	ADT_uadmin_ftrace,
	AUE_uadmin_ftrace,
	4,
	&XX_uadmin_ftrace[0],
	&XX_uadmin_ftrace[0]
};
static struct entry XX_uadmin_reboot[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_uadmin_reboot[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr8[0],	&(XX_uadmin_reboot[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_uadmin_reboot[3]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_uadmin_reboot = {
	0,
	ADT_uadmin_reboot,
	AUE_uadmin_reboot,
	4,
	&XX_uadmin_reboot[0],
	&XX_uadmin_reboot[0]
};
static struct entry XX_uadmin_remount[2] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_uadmin_remount[1]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_uadmin_remount = {
	0,
	ADT_uadmin_remount,
	AUE_uadmin_remount,
	2,
	&XX_uadmin_remount[0],
	&XX_uadmin_remount[0]
};
static struct entry XX_uadmin_shutdown[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_uadmin_shutdown[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr8[0],	&(XX_uadmin_shutdown[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_uadmin_shutdown[3]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_uadmin_shutdown = {
	0,
	ADT_uadmin_shutdown,
	AUE_uadmin_shutdown,
	4,
	&XX_uadmin_shutdown[0],
	&XX_uadmin_shutdown[0]
};
static struct entry XX_uadmin_swapctl[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_uadmin_swapctl[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr8[0],	&(XX_uadmin_swapctl[2]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_uadmin_swapctl = {
	0,
	ADT_uadmin_swapctl,
	AUE_uadmin_swapctl,
	3,
	&XX_uadmin_swapctl[0],
	&XX_uadmin_swapctl[0]
};
static struct entry XX_uadmin_thaw[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_uadmin_thaw[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr8[0],	&(XX_uadmin_thaw[2]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_uadmin_thaw = {
	0,
	ADT_uadmin_thaw,
	AUE_uadmin_thaw,
	3,
	&XX_uadmin_thaw[0],
	&XX_uadmin_thaw[0]
};
static struct entry XX_uauth[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_uauth[1]),
		0,	0,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_uauth[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_uauth[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_uauth = {
	0,
	ADT_uauth,
	AUE_uauth,
	4,
	&XX_uauth[0],
	&XX_uauth[0]
};
static struct entry XX_usermgr_add[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_usermgr_add[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_add[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_add[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_add[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_usermgr_add[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_add[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_usermgr_add = {
	0,
	ADT_usermgr_add,
	AUE_usermgr_add,
	7,
	&XX_usermgr_add[0],
	&XX_usermgr_add[0]
};
static struct entry XX_usermgr_delete[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_usermgr_delete[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_delete[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_delete[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_delete[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_usermgr_delete[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_delete[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_usermgr_delete = {
	0,
	ADT_usermgr_delete,
	AUE_usermgr_delete,
	7,
	&XX_usermgr_delete[0],
	&XX_usermgr_delete[0]
};
static struct entry XX_usermgr_modify[7] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_usermgr_modify[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_modify[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_modify[3]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_modify[4]),
		0,	1,	0,	NULL},
	{AUT_UAUTH,	1,	&adr1[0],	&(XX_usermgr_modify[5]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_usermgr_modify[6]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_usermgr_modify = {
	0,
	ADT_usermgr_modify,
	AUE_usermgr_modify,
	7,
	&XX_usermgr_modify[0],
	&XX_usermgr_modify[0]
};
static struct entry XX_vscan_quarantine[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_vscan_quarantine[1]),
		0,	0,	0,	NULL},
	{AUT_PATH,	1,	&adr1[0],	&(XX_vscan_quarantine[2]),
		0,	1,	0,	NULL},
	{AUT_TEXT,	2,	&adr9[0],	&(XX_vscan_quarantine[3]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_vscan_quarantine = {
	0,
	ADT_vscan_quarantine,
	AUE_vscan_quarantine,
	4,
	&XX_vscan_quarantine[0],
	&XX_vscan_quarantine[0]
};
static struct entry XX_zlogin[3] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_zlogin[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_zlogin[2]),
		0,	0,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_zlogin = {
	0,
	ADT_zlogin,
	AUE_zlogin,
	3,
	&XX_zlogin[0],
	&XX_zlogin[0]
};
static struct entry XX_zone_state[4] = {
	{AUT_SUBJECT,	1,	NULL,	&(XX_zone_state[1]),
		0,	0,	0,	NULL},
	{AUT_TEXT,	1,	&adr1[0],	&(XX_zone_state[2]),
		0,	1,	0,	NULL},
	{AUT_ZONENAME,	1,	&adr1[0],	&(XX_zone_state[3]),
		0,	1,	0,	NULL},
	{AUT_RETURN,	1,	NULL,	NULL,
		0,	0,	0,	NULL}
};
static struct translation X_zone_state = {
	0,
	ADT_zone_state,
	AUE_zone_state,
	4,
	&XX_zone_state[0],
	&XX_zone_state[0]
};
adt_translation_t *adt_xlate_table[134] = {
	&X_admin_authenticate,
	&X_attach,
	&X_cpu_ondemand,
	&X_cpu_performance,
	&X_cpu_threshold,
	&X_detach,
	&X_dladm_create_secobj,
	&X_dladm_delete_secobj,
	&X_file_copy,
	&X_file_relabel,
	&X_filesystem_add,
	&X_filesystem_delete,
	&X_filesystem_modify,
	&X_hotplug_set,
	&X_hotplug_state,
	&X_ilb_add_server,
	&X_ilb_create_healthcheck,
	&X_ilb_create_rule,
	&X_ilb_create_servergroup,
	&X_ilb_delete_healthcheck,
	&X_ilb_delete_rule,
	&X_ilb_delete_servergroup,
	&X_ilb_disable_rule,
	&X_ilb_disable_server,
	&X_ilb_enable_rule,
	&X_ilb_enable_server,
	&X_ilb_remove_server,
	&X_inetd_connect,
	&X_inetd_copylimit,
	&X_inetd_failrate,
	&X_inetd_ratelimit,
	&X_init_solaris,
	&X_login,
	&X_logout,
	&X_ndmp_backup,
	&X_ndmp_connect,
	&X_ndmp_disconnect,
	&X_ndmp_restore,
	&X_netcfg_remove,
	&X_netcfg_update,
	&X_network_add,
	&X_network_delete,
	&X_network_modify,
	&X_newgrp_login,
	&X_nwam_disable,
	&X_nwam_enable,
	&X_passwd,
	&X_pool_export,
	&X_pool_import,
	&X_printer_add,
	&X_printer_delete,
	&X_printer_modify,
	&X_prof_cmd,
	&X_remove,
	&X_rlogin,
	&X_role_login,
	&X_role_logout,
	&X_scheduledjob_add,
	&X_scheduledjob_delete,
	&X_scheduledjob_modify,
	&X_screenlock,
	&X_screenunlock,
	&X_serialport_add,
	&X_serialport_delete,
	&X_serialport_modify,
	&X_smbd_logoff,
	&X_smbd_session,
	&X_smf_annotation,
	&X_smf_attach_snap,
	&X_smf_change_prop,
	&X_smf_clear,
	&X_smf_create,
	&X_smf_create_npg,
	&X_smf_create_pg,
	&X_smf_create_prop,
	&X_smf_create_snap,
	&X_smf_degrade,
	&X_smf_delete,
	&X_smf_delete_npg,
	&X_smf_delete_pg,
	&X_smf_delete_prop,
	&X_smf_delete_snap,
	&X_smf_disable,
	&X_smf_enable,
	&X_smf_immediate_degrade,
	&X_smf_immediate_maintenance,
	&X_smf_immtmp_maintenance,
	&X_smf_maintenance,
	&X_smf_milestone,
	&X_smf_read_prop,
	&X_smf_refresh,
	&X_smf_restart,
	&X_smf_tmp_disable,
	&X_smf_tmp_enable,
	&X_smf_tmp_maintenance,
	&X_ssh,
	&X_su,
	&X_su_logout,
	&X_telnet,
	&X_tpm_certifyselftest,
	&X_tpm_continueselftest,
	&X_tpm_disableforceclear,
	&X_tpm_disableownerclear,
	&X_tpm_fieldupgrade,
	&X_tpm_forceclear,
	&X_tpm_ownerclear,
	&X_tpm_ownersetdisable,
	&X_tpm_physicaldeactivate,
	&X_tpm_physicaldisable,
	&X_tpm_physicalenable,
	&X_tpm_physicalpresence,
	&X_tpm_resetlockvalue,
	&X_tpm_selftestfull,
	&X_tpm_setoperatorauth,
	&X_tpm_setownerinstall,
	&X_tpm_settempdeactivated,
	&X_tpm_takeownership,
	&X_uadmin_config,
	&X_uadmin_dump,
	&X_uadmin_freeze,
	&X_uadmin_ftrace,
	&X_uadmin_reboot,
	&X_uadmin_remount,
	&X_uadmin_shutdown,
	&X_uadmin_swapctl,
	&X_uadmin_thaw,
	&X_uauth,
	&X_usermgr_add,
	&X_usermgr_delete,
	&X_usermgr_modify,
	&X_vscan_quarantine,
	&X_zlogin,
	&X_zone_state,
	NULL
};

void
adt_preload(au_event_t event_id, adt_event_data_t *event_data)
{
	switch (event_id) {
	case ADT_passwd:
		event_data->adt_passwd.uid = AU_NOAUDITID;
		break;
	case ADT_prof_cmd:
		event_data->adt_prof_cmd.proc_auid = AU_NOAUDITID;
		event_data->adt_prof_cmd.proc_euid = AU_NOAUDITID;
		event_data->adt_prof_cmd.proc_egid = AU_NOAUDITID;
		event_data->adt_prof_cmd.proc_ruid = AU_NOAUDITID;
		event_data->adt_prof_cmd.proc_rgid = AU_NOAUDITID;
		break;
	case ADT_ndmp_backup:
		event_data->adt_ndmp_backup.remote_dest = -1;
		break;
	case ADT_ndmp_restore:
		event_data->adt_ndmp_restore.remote_source = -1;
		break;
	default:
		break;
	}
}
#endif

/* message lists */

static char *msg_fail_value[24] = {
	"Attribute update",
	"Password update",
	"bad username",
	"authorization failed",
	"bad uid",
	"unknown failure",
	"password expired",
	"Account is locked",
	"Bad dial up",
	"Invalid ID",
	"Invalid password",
	"Not on console",
	"Too many failed attempts",
	"Protocol failure",
	"Excluded user",
	"No anonymous",
	"Invalid command",
	"Standard input not a tty line",
	"Program failure",
	"chdir to home directory",
	"Input line too long.",
	"login device override",
	"authorization bypass",
	"login disabled"
};
/* Deprecated message list */
static char *msg_login_text[10] = {
	NULL,
	"Account is locked",
	"Bad dial up",
	"Invalid ID",
	"Invalid password",
	"Not on console",
	"Too many failed attempts",
	"Protocol failure",
	"Excluded user",
	"No anonymous"
};
static char *msg_tpm_e[103] = {
	"Authentication failed",
	"The index to a PCR, DIR or other register is incorrect",
	"One or more parameter is bad",
	"auditing of the operation failed.",
	"clear operations now physical access",
	"The TPM is deactivated",
	"The TPM is disabled",
	"The target command has been disabled",
	"The operation failed",
	"The ordinal was unknown or inconsistent",
	"The ability to install an owner is disabled",
	"The key handle can not be interpreted",
	"The key handle points to an invalid key",
	"Unacceptable encryption scheme",
	"Migration authorization failed",
	"PCR information could not be interpreted",
	"No room to load key.",
	"There is no SRK set",
	"An encrypted blob is invalid or was not created by this TPM",
	"There is already an Owner",
	"The TPM has insufficient internal resources",
	"A random string was too short",
	"The TPM does not have the space to perform the operation.",
	"The named PCR value does not match the current PCR value.",
	"The paramSize argument has the incorrect value",
	"There is no existing SHA-1 thread.",
	"SHA-1 thread encountered an error.",
	"Self-test has failed and the TPM has shutdown.",
	"The auth for the second key failed authorization",
	"The tag value sent to for a command is invalid",
	"An IO error occurred transmitting information to the TPM",
	"The encryption process had a problem.",
	"The decryption process did not complete.",
	"An invalid handle was used.",
	"The TPM does not a EK installed",
	"The usage of a key is not allowed",
	"The submitted entity type is not allowed",
	"The command was received in the wrong sequence",
	"Signed data cannot include additional DER information",
	"The key properties are not supported by this TPM",
	"The migration properties of this key are incorrect.",
	"Incorrect signature or encryption scheme",
	"The size of the data parameter is bad",
	"A mode parameter is bad",
	"physicalPresence or physicalPresenceLock bits have wrong value",
	"The TPM cannot perform this version of the capability",
	"The TPM does not allow for wrapped transport sessions",
	"TPM audit construction failed for failed command",
	"TPM audit construction failed for successful command",
	"PCR register does not have the resettable attribute",
	"PCR register requires locality",
	"Make identity blob not properly typed",
	"Resource type does not match actual resource",
	"Command only available when TPM is in FIPS mode",
	"The command is attempting to use an invalid family ID",
	"The permission to manipulate the NV storage is not available",
	"The operation requires a signed command",
	"Wrong operation to load an NV key",
	"NV_LoadKey blob requires both owner and blob authorization",
	"The NV area is locked and not writable",
	"The locality is incorrect for the attempted operation",
	"The NV area is read only and can't be written to",
	"There is no protection on the write to the NV area",
	"The family count value does not match",
	"The NV area has already been written to",
	"The NV area attributes conflict",
	"The tag and version are invalid or inconsistent",
	"The key evicted by the TPM Owner.",
	"The counter handle is incorrect",
	"The write is not a complete write of the area",
	"The gap between saved context counts is too large",
	"Max number of NV writes without owner has been exceeded",
	"No operator AuthData value is set",
	"The resource pointed to by context is not loaded",
	"The delegate administration is locked",
	"Attempt to manage a family other then the delegated family",
	"Delegation table management not enabled",
	"Command executed outside of exclusive transport session",
	"Attempt to context save a owner evict controlled key",
	"DAA command has no resources available to execute the command",
	"The consistency check on DAA parameter inputData0 has failed.",
	"The consistency check on DAA parameter inputData1 has failed.",
	"The consistency check on DAA_issuerSettings has failed.",
	"The consistency check on DAA_tpmSpecific has failed.",
	"Atomic process indicated by DAA command is not the expected process.",
	"Inconsistent issuer validity",
	"The consistency check on w has failed.",
	"The handle is incorrect",
	"Delegation is not correct",
	"The context blob is invalid",
	"Too many contexts held by the TPM",
	"Migration authority signature validation failure",
	"Migration destination not authenticated",
	"Migration source incorrect",
	"Incorrect migration authority",
	"Attempt to revoke the EK and the EK is not revocable",
	"Bad signature of CMK ticket",
	"There is no room in the context list for additional contexts",
	"The TPM is too busy to respond to the command immediately",
	"SelfTestFull has not been run",
	"The TPM is currently executing a full selftest",
	"TPM is defending against dictionary attacks",
	NULL
};
static char *msg_uadmin_fcn[20] = {
	"Halt the processor(s)",
	"Halt the processor(s) and turn off the power",
	"Reboot the system using the kernel file",
	"Interactive reboot",
	"Save the system state to the state file",
	"Check if system supports suspend to disk",
	"Force suspend to disk even when threads of user applications are not suspendable",
	"Save the system state to memory",
	"Check if system supports suspend to memory",
	"Single-user reboot",
	"Single-user interactive reboot",
	"Do not sync filesystems on next A_DUMP",
	"Reboot bypassing BIOS and boot loader",
	"Check if system supports reboot bypassing BIOS and boot loader",
	"Update boot configuration parameters",
	"Prepare for AD_REUSABLE",
	"Create reusable statefile",
	"Revert to normal CPR mode (not reusable)",
	"ftrace start",
	"ftrace stop"
};

struct msg_text adt_msg_text[5] = {
	{0, -1, NULL, -2000},
	{0, 23, msg_fail_value, -1000},
	{0, 9, msg_login_text, 0},
	{0, 102, msg_tpm_e, -4000},
	{0, 19, msg_uadmin_fcn, -3000}
};
