#define	TI_MODULEID	0x0
#define	TI_TLSOFFSET	0x8
#define	SIZEOF_TLS_T	0x10
#define	TLS_DATA	0x0
#define	TLS_SIZE	0x8
#define UL_TLSENT UL_TLS+TLS_DATA
#define UL_NTLSENT UL_TLS+TLS_SIZE
#define	UL_TLS	0x48
#define	UL_USTACK	0xa8
#define	UL_VFORK	0xfc
#define	UL_SCHEDCTL	0x128
#define	UL_SCHEDCTL_CALLED	0x120
#define	UL_SIGLINK	0x218
#define	UL_SIGMASK	0x270
#define	SS_SP	0x0
#define	SS_SIZE	0x8
#define UC_MCONTEXT_GREGS UC_MCONTEXT+GREGS
#define	SIZEOF_UCONTEXT_T	0x360
#define	UC_MCONTEXT	0x40
#define	GREGS	0x0
#define	GREGS_INCR	0x8
#define	SIZEOF_SIGJMP_BUF	0x400
#define	MUTEX_LOCK_WORD	0xc
#define	WAITER_MASK	0x00ff0000
#define	SIG_SETMASK	0x3
#define	MASKSET0	0xffbffeff
#define	MASKSET1	0xffffffff
#define	MASKSET2	0x1ff
#define	MASKSET3	0x0
#define	SIGSEGV	0xb
#define	RIP_OFF	0x88
#define	RAX_OFF	0x70
#define	RSP_OFF	0xa0
