/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../uts/common/rpcsvc/nlm_prot.h"

#ifndef _KERNEL
#include <stdlib.h>
#endif /* !_KERNEL */


bool_t
xdr_nlm_stats(xdrs, objp)
	XDR *xdrs;
	nlm_stats *objp;
{

	rpc_inline_t *buf;

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_holder(xdrs, objp)
	XDR *xdrs;
	nlm_holder *objp;
{

	rpc_inline_t *buf;

	if (!xdr_bool(xdrs, &objp->exclusive))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->svid))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->oh))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->l_offset))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->l_len))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_testrply(xdrs, objp)
	XDR *xdrs;
	nlm_testrply *objp;
{

	rpc_inline_t *buf;

	if (!xdr_nlm_stats(xdrs, &objp->stat))
		return (FALSE);
	switch (objp->stat) {
	case nlm_denied:
		if (!xdr_nlm_holder(xdrs, &objp->nlm_testrply_u.holder))
			return (FALSE);
		break;
	}
	return (TRUE);
}

bool_t
xdr_nlm_stat(xdrs, objp)
	XDR *xdrs;
	nlm_stat *objp;
{

	rpc_inline_t *buf;

	if (!xdr_nlm_stats(xdrs, &objp->stat))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_res(xdrs, objp)
	XDR *xdrs;
	nlm_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_nlm_stat(xdrs, &objp->stat))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_testres(xdrs, objp)
	XDR *xdrs;
	nlm_testres *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_nlm_testrply(xdrs, &objp->stat))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_lock(xdrs, objp)
	XDR *xdrs;
	nlm_lock *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->caller_name, LM_MAXSTRLEN))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->fh))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->oh))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->svid))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->l_offset))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->l_len))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_lockargs(xdrs, objp)
	XDR *xdrs;
	nlm_lockargs *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->block))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->exclusive))
		return (FALSE);
	if (!xdr_nlm_lock(xdrs, &objp->alock))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->reclaim))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_cancargs(xdrs, objp)
	XDR *xdrs;
	nlm_cancargs *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->block))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->exclusive))
		return (FALSE);
	if (!xdr_nlm_lock(xdrs, &objp->alock))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_testargs(xdrs, objp)
	XDR *xdrs;
	nlm_testargs *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->exclusive))
		return (FALSE);
	if (!xdr_nlm_lock(xdrs, &objp->alock))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_unlockargs(xdrs, objp)
	XDR *xdrs;
	nlm_unlockargs *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_nlm_lock(xdrs, &objp->alock))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_fsh_mode(xdrs, objp)
	XDR *xdrs;
	fsh_mode *objp;
{

	rpc_inline_t *buf;

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_fsh_access(xdrs, objp)
	XDR *xdrs;
	fsh_access *objp;
{

	rpc_inline_t *buf;

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_share(xdrs, objp)
	XDR *xdrs;
	nlm_share *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->caller_name, LM_MAXSTRLEN))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->fh))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->oh))
		return (FALSE);
	if (!xdr_fsh_mode(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_fsh_access(xdrs, &objp->access))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_shareargs(xdrs, objp)
	XDR *xdrs;
	nlm_shareargs *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_nlm_share(xdrs, &objp->share))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->reclaim))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_shareres(xdrs, objp)
	XDR *xdrs;
	nlm_shareres *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_nlm_stats(xdrs, &objp->stat))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->sequence))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_notify(xdrs, objp)
	XDR *xdrs;
	nlm_notify *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->name, LM_MAXNAMELEN))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_stats(xdrs, objp)
	XDR *xdrs;
	nlm4_stats *objp;
{

	rpc_inline_t *buf;

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_holder(xdrs, objp)
	XDR *xdrs;
	nlm4_holder *objp;
{

	rpc_inline_t *buf;

	if (!xdr_bool(xdrs, &objp->exclusive))
		return (FALSE);
	if (!xdr_int32(xdrs, &objp->svid))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->oh))
		return (FALSE);
	if (!xdr_uint64(xdrs, &objp->l_offset))
		return (FALSE);
	if (!xdr_uint64(xdrs, &objp->l_len))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_testrply(xdrs, objp)
	XDR *xdrs;
	nlm4_testrply *objp;
{

	rpc_inline_t *buf;

	if (!xdr_nlm4_stats(xdrs, &objp->stat))
		return (FALSE);
	switch (objp->stat) {
	case nlm4_denied:
		if (!xdr_nlm4_holder(xdrs, &objp->nlm4_testrply_u.holder))
			return (FALSE);
		break;
	}
	return (TRUE);
}

bool_t
xdr_nlm4_stat(xdrs, objp)
	XDR *xdrs;
	nlm4_stat *objp;
{

	rpc_inline_t *buf;

	if (!xdr_nlm4_stats(xdrs, &objp->stat))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_res(xdrs, objp)
	XDR *xdrs;
	nlm4_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_nlm4_stat(xdrs, &objp->stat))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_testres(xdrs, objp)
	XDR *xdrs;
	nlm4_testres *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_nlm4_testrply(xdrs, &objp->stat))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_lock(xdrs, objp)
	XDR *xdrs;
	nlm4_lock *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->caller_name, LM_MAXSTRLEN))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->fh))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->oh))
		return (FALSE);
	if (!xdr_int32(xdrs, &objp->svid))
		return (FALSE);
	if (!xdr_uint64(xdrs, &objp->l_offset))
		return (FALSE);
	if (!xdr_uint64(xdrs, &objp->l_len))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_lockargs(xdrs, objp)
	XDR *xdrs;
	nlm4_lockargs *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->block))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->exclusive))
		return (FALSE);
	if (!xdr_nlm4_lock(xdrs, &objp->alock))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->reclaim))
		return (FALSE);
	if (!xdr_int32(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_cancargs(xdrs, objp)
	XDR *xdrs;
	nlm4_cancargs *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->block))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->exclusive))
		return (FALSE);
	if (!xdr_nlm4_lock(xdrs, &objp->alock))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_testargs(xdrs, objp)
	XDR *xdrs;
	nlm4_testargs *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->exclusive))
		return (FALSE);
	if (!xdr_nlm4_lock(xdrs, &objp->alock))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_unlockargs(xdrs, objp)
	XDR *xdrs;
	nlm4_unlockargs *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_nlm4_lock(xdrs, &objp->alock))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_share(xdrs, objp)
	XDR *xdrs;
	nlm4_share *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->caller_name, LM_MAXSTRLEN))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->fh))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->oh))
		return (FALSE);
	if (!xdr_fsh_mode(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_fsh_access(xdrs, &objp->access))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_shareargs(xdrs, objp)
	XDR *xdrs;
	nlm4_shareargs *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_nlm4_share(xdrs, &objp->share))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->reclaim))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_shareres(xdrs, objp)
	XDR *xdrs;
	nlm4_shareres *objp;
{

	rpc_inline_t *buf;

	if (!xdr_netobj(xdrs, &objp->cookie))
		return (FALSE);
	if (!xdr_nlm4_stats(xdrs, &objp->stat))
		return (FALSE);
	if (!xdr_int32(xdrs, &objp->sequence))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm4_notify(xdrs, objp)
	XDR *xdrs;
	nlm4_notify *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->name, LM_MAXNAMELEN))
		return (FALSE);
	if (!xdr_int32(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nlm_sm_status(xdrs, objp)
	XDR *xdrs;
	nlm_sm_status *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->mon_name, LM_MAXSTRLEN))
		return (FALSE);
	if (!xdr_int32(xdrs, &objp->state))
		return (FALSE);
	if (!xdr_opaque(xdrs, objp->priv, 16))
		return (FALSE);
	return (TRUE);
}
