/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../uts/common/rpcsvc/nsm_addr.h"

#ifndef _KERNEL
#include <stdlib.h>
#endif /* !_KERNEL */

/*
 * Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 *
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License, Version 1.0 only
 * (the "License").  You may not use this file except in compliance
 * with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

#pragma ident	"%Z%%M%	%I%	%E% SMI"

/* from nsm_addr.x */

/*
 * This is the definition for the REG procedure which is used
 * to register name/address pairs with statd.
 */


bool_t
xdr_nsm_addr_res(xdrs, objp)
	XDR *xdrs;
	nsm_addr_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_reg1args(xdrs, objp)
	XDR *xdrs;
	reg1args *objp;
{

	rpc_inline_t *buf;

	if (!xdr_u_int(xdrs, &objp->family))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->name, 1024))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->address))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_reg1res(xdrs, objp)
	XDR *xdrs;
	reg1res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_nsm_addr_res(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

/*
 * This is the definition for the UNREG procedure which is used
 * to unregister an address (and its associated name, if that name
 * has no other addresses registered with it) with statd.
 */

bool_t
xdr_unreg1args(xdrs, objp)
	XDR *xdrs;
	unreg1args *objp;
{

	rpc_inline_t *buf;

	if (!xdr_u_int(xdrs, &objp->family))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->name, 1024))
		return (FALSE);
	if (!xdr_netobj(xdrs, &objp->address))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_unreg1res(xdrs, objp)
	XDR *xdrs;
	unreg1res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_nsm_addr_res(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

/*
 * This is the definition for the NSM address registration network
 * protocol which is used to privately support address registration
 * with the status daemon statd (NSM).
 */
