/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../uts/common/rpc/rpc_sztypes.h"

#ifndef _KERNEL
#include <stdlib.h>
#endif /* !_KERNEL */

#pragma ident	"%Z%%M%	%I%	%E% SMI"

bool_t
xdr_uint64(xdrs, objp)
	XDR *xdrs;
	uint64 *objp;
{

	rpc_inline_t *buf;

	if (!xdr_u_longlong_t(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_int64(xdrs, objp)
	XDR *xdrs;
	int64 *objp;
{

	rpc_inline_t *buf;

	if (!xdr_longlong_t(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_uint32(xdrs, objp)
	XDR *xdrs;
	uint32 *objp;
{

	rpc_inline_t *buf;

	if (!xdr_u_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_int32(xdrs, objp)
	XDR *xdrs;
	int32 *objp;
{

	rpc_inline_t *buf;

	if (!xdr_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}
