/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../head/rpcsvc/rusers.h"

#ifndef _KERNEL
#include <stdlib.h>
#endif /* !_KERNEL */

/*
 * Find out about remote users
 */

bool_t
xdr_rusers_utmp(xdrs, objp)
	XDR *xdrs;
	rusers_utmp *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->ut_user, RUSERS_MAXUSERLEN))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->ut_line, RUSERS_MAXLINELEN))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->ut_host, RUSERS_MAXHOSTLEN))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->ut_type))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->ut_time))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->ut_idle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_utmp_array(xdrs, objp)
	XDR *xdrs;
	utmp_array *objp;
{

	rpc_inline_t *buf;

	if (!xdr_array(xdrs, (char **)&objp->utmp_array_val, (u_int *) &objp->utmp_array_len, ~0,
		sizeof (rusers_utmp), (xdrproc_t)xdr_rusers_utmp))
		return (FALSE);
	return (TRUE);
}
