/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../uts/common/rpcsvc/sm_inter.h"

#ifndef _KERNEL
#include <stdlib.h>
#endif /* !_KERNEL */

/*
 * Copyright (c) 1986, 1994 by Sun Microsystems, Inc.
 * All rights reserved.
 */
/* from sm_inter.x */

bool_t
xdr_sm_name(xdrs, objp)
	XDR *xdrs;
	sm_name *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->mon_name, SM_MAXSTRLEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_my_id(xdrs, objp)
	XDR *xdrs;
	my_id *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->my_name, SM_MAXSTRLEN))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->my_prog))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->my_vers))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->my_proc))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_mon_id(xdrs, objp)
	XDR *xdrs;
	mon_id *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->mon_name, SM_MAXSTRLEN))
		return (FALSE);
	if (!xdr_my_id(xdrs, &objp->my_id))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_mon(xdrs, objp)
	XDR *xdrs;
	mon *objp;
{

	rpc_inline_t *buf;

	if (!xdr_mon_id(xdrs, &objp->mon_id))
		return (FALSE);
	if (!xdr_opaque(xdrs, objp->priv, 16))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_sm_stat(xdrs, objp)
	XDR *xdrs;
	sm_stat *objp;
{

	rpc_inline_t *buf;

	if (!xdr_int(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_sm_res(xdrs, objp)
	XDR *xdrs;
	sm_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_sm_stat_res(xdrs, objp)
	XDR *xdrs;
	sm_stat_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_sm_res(xdrs, &objp->res_stat))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_sm_status(xdrs, objp)
	XDR *xdrs;
	sm_status *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->mon_name, SM_MAXSTRLEN))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->state))
		return (FALSE);
	if (!xdr_opaque(xdrs, objp->priv, 16))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_stat_chge(xdrs, objp)
	XDR *xdrs;
	stat_chge *objp;
{

	rpc_inline_t *buf;

	if (!xdr_string(xdrs, &objp->mon_name, SM_MAXSTRLEN))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}
