/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../head/rpcsvc/spray.h"

#ifndef _KERNEL
#include <stdlib.h>
#endif /* !_KERNEL */

/*
 * Copyright (c) 1987, 1991 by Sun Microsystems, Inc.
 */
/* from spray.x */

bool_t
xdr_spraytimeval(xdrs, objp)
	XDR *xdrs;
	spraytimeval *objp;
{

	rpc_inline_t *buf;

	if (!xdr_u_int(xdrs, &objp->sec))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->usec))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_spraycumul(xdrs, objp)
	XDR *xdrs;
	spraycumul *objp;
{

	rpc_inline_t *buf;

	if (!xdr_u_int(xdrs, &objp->counter))
		return (FALSE);
	if (!xdr_spraytimeval(xdrs, &objp->clock))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_sprayarr(xdrs, objp)
	XDR *xdrs;
	sprayarr *objp;
{

	rpc_inline_t *buf;

	if (!xdr_bytes(xdrs, (char **)&objp->sprayarr_val, (u_int *) &objp->sprayarr_len, SPRAYMAX))
		return (FALSE);
	return (TRUE);
}
