/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _KEY_XDR_H_RPCGEN
#define	_KEY_XDR_H_RPCGEN

#include <rpc/rpc.h>
#define	WBKU_AES_128_OID "2.16.840.1.101.3.4.1.2"
#define	WBKU_DES3_OID "1.3.6.1.4.1.4929.1.8"
#define	WBKU_HMAC_SHA1_OID "1.3.6.1.5.5.8.1.2"
#define	WBKU_RSA_OID "1.2.840.113549.1.1.1"
#define	WBKU_MAX_KEYLEN 1024

struct wbku_key {
	bool_t wk_master;
	char *wk_oid;
	struct {
		u_int KEYDATA_len;
		char *KEYDATA_val;
	} KEYDATA;
};
typedef struct wbku_key wbku_key;
#define wk_key_len KEYDATA.KEYDATA_len
#define wk_key_val KEYDATA.KEYDATA_val

typedef struct {
	u_int wbku_keystore_len;
	wbku_key *wbku_keystore_val;
} wbku_keystore;

/* the xdr functions */
extern bool_t xdr_wbku_key();
extern bool_t xdr_wbku_keystore();

#endif /* !_KEY_XDR_H_RPCGEN */
