/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gssd_prot.h"

#ifndef _KERNEL
#include <stdlib.h>
#endif /* !_KERNEL */

/*
 * Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 */

/*
 *  RPC protocol information for gssd, the usermode daemon that
 *  assists the kernel with gssapi. It is gssd that executes all
 *  gssapi calls except for some such as gss_sign(), and
 *  gss_verify(), which are executed in the kernel itself.
 *
 *  File generated from gssd.x
 */

#define	NO 0
#define	YES 1
#define	FOREVER 1

#include <sys/types.h>
#include <sys/time.h>
#include <rpc/auth_sys.h>
#ifndef _KERNEL
#include <locale.h>
#endif /* not _KERNEL */

#ifdef _KERNEL
extern void killgssd_handle(CLIENT *);
extern CLIENT *getgssd_handle(void);
#endif /* _KERNEL */


bool_t
xdr_OM_UINT32(xdrs, objp)
	XDR *xdrs;
	OM_UINT32 *objp;
{

	rpc_inline_t *buf;

	if (!xdr_u_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GSS_CTX_ID_T(xdrs, objp)
	XDR *xdrs;
	GSS_CTX_ID_T *objp;
{

	rpc_inline_t *buf;

	if (!xdr_bytes(xdrs, (char **)&objp->GSS_CTX_ID_T_val, (u_int *) &objp->GSS_CTX_ID_T_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GSS_CRED_ID_T(xdrs, objp)
	XDR *xdrs;
	GSS_CRED_ID_T *objp;
{

	rpc_inline_t *buf;

	if (!xdr_bytes(xdrs, (char **)&objp->GSS_CRED_ID_T_val, (u_int *) &objp->GSS_CRED_ID_T_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GSS_OID(xdrs, objp)
	XDR *xdrs;
	GSS_OID *objp;
{

	rpc_inline_t *buf;

	if (!xdr_bytes(xdrs, (char **)&objp->GSS_OID_val, (u_int *) &objp->GSS_OID_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GSS_BUFFER_T(xdrs, objp)
	XDR *xdrs;
	GSS_BUFFER_T *objp;
{

	rpc_inline_t *buf;

	if (!xdr_bytes(xdrs, (char **)&objp->GSS_BUFFER_T_val, (u_int *) &objp->GSS_BUFFER_T_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GSSCRED_GIDS(xdrs, objp)
	XDR *xdrs;
	GSSCRED_GIDS *objp;
{

	rpc_inline_t *buf;

	if (!xdr_array(xdrs, (char **)&objp->GSSCRED_GIDS_val, (u_int *) &objp->GSSCRED_GIDS_len, ~0,
		sizeof (gid_t), (xdrproc_t)xdr_gid_t))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GSS_OID_SET(xdrs, objp)
	XDR *xdrs;
	GSS_OID_SET *objp;
{

	rpc_inline_t *buf;

	if (!xdr_array(xdrs, (char **)&objp->GSS_OID_SET_val, (u_int *) &objp->GSS_OID_SET_len, ~0,
		sizeof (GSS_OID), (xdrproc_t)xdr_GSS_OID))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GSS_CHANNEL_BINDINGS_STRUCT(xdrs, objp)
	XDR *xdrs;
	GSS_CHANNEL_BINDINGS_STRUCT *objp;
{

	rpc_inline_t *buf;

	if (!xdr_int(xdrs, &objp->present))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->initiator_addrtype))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->initiator_address))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->acceptor_addrtype))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->acceptor_address))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->application_data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GSS_CHANNEL_BINDINGS(xdrs, objp)
	XDR *xdrs;
	GSS_CHANNEL_BINDINGS *objp;
{

	rpc_inline_t *buf;

	if (!xdr_GSS_CHANNEL_BINDINGS_STRUCT(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_acquire_cred_arg(xdrs, objp)
	XDR *xdrs;
	gss_acquire_cred_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->desired_name))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->name_type))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->time_req))
		return (FALSE);
	if (!xdr_GSS_OID_SET(xdrs, &objp->desired_mechs))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->cred_usage))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_acquire_cred_res(xdrs, objp)
	XDR *xdrs;
	gss_acquire_cred_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_CRED_ID_T(xdrs, &objp->output_cred_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_cred_verifier))
		return (FALSE);
	if (!xdr_GSS_OID_SET(xdrs, &objp->actual_mechs))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->time_rec))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_add_cred_arg(xdrs, objp)
	XDR *xdrs;
	gss_add_cred_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_GSS_CRED_ID_T(xdrs, &objp->input_cred_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_cred_verifier))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->desired_name))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->name_type))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->desired_mech_type))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->cred_usage))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->initiator_time_req))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->acceptor_time_req))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_add_cred_res(xdrs, objp)
	XDR *xdrs;
	gss_add_cred_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_OID_SET(xdrs, &objp->actual_mechs))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->initiator_time_rec))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->acceptor_time_rec))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_release_cred_arg(xdrs, objp)
	XDR *xdrs;
	gss_release_cred_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_cred_verifier))
		return (FALSE);
	if (!xdr_GSS_CRED_ID_T(xdrs, &objp->cred_handle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_release_cred_res(xdrs, objp)
	XDR *xdrs;
	gss_release_cred_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_init_sec_context_arg(xdrs, objp)
	XDR *xdrs;
	gss_init_sec_context_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_GSS_CRED_ID_T(xdrs, &objp->claimant_cred_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_cred_verifier))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->target_name))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->name_type))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->mech_type))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->req_flags))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->time_req))
		return (FALSE);
	if (!xdr_GSS_CHANNEL_BINDINGS(xdrs, &objp->input_chan_bindings))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->input_token))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_init_sec_context_res(xdrs, objp)
	XDR *xdrs;
	gss_init_sec_context_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->actual_mech_type))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->output_token))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->ret_flags))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->time_rec))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_accept_sec_context_arg(xdrs, objp)
	XDR *xdrs;
	gss_accept_sec_context_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_GSS_CRED_ID_T(xdrs, &objp->verifier_cred_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_cred_verifier))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->input_token_buffer))
		return (FALSE);
	if (!xdr_GSS_CHANNEL_BINDINGS(xdrs, &objp->input_chan_bindings))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_accept_sec_context_res(xdrs, objp)
	XDR *xdrs;
	gss_accept_sec_context_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->src_name))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->mech_type))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->output_token))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->ret_flags))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->time_rec))
		return (FALSE);
	if (!xdr_GSS_CRED_ID_T(xdrs, &objp->delegated_cred_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_process_context_token_arg(xdrs, objp)
	XDR *xdrs;
	gss_process_context_token_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->token_buffer))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_process_context_token_res(xdrs, objp)
	XDR *xdrs;
	gss_process_context_token_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_delete_sec_context_arg(xdrs, objp)
	XDR *xdrs;
	gss_delete_sec_context_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_delete_sec_context_res(xdrs, objp)
	XDR *xdrs;
	gss_delete_sec_context_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->output_token))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_export_sec_context_arg(xdrs, objp)
	XDR *xdrs;
	gss_export_sec_context_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_export_sec_context_res(xdrs, objp)
	XDR *xdrs;
	gss_export_sec_context_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->output_token))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_import_sec_context_arg(xdrs, objp)
	XDR *xdrs;
	gss_import_sec_context_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_GSS_BUFFER_T(xdrs, &objp->input_token))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_import_sec_context_res(xdrs, objp)
	XDR *xdrs;
	gss_import_sec_context_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_context_time_arg(xdrs, objp)
	XDR *xdrs;
	gss_context_time_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_context_time_res(xdrs, objp)
	XDR *xdrs;
	gss_context_time_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->time_rec))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_sign_arg(xdrs, objp)
	XDR *xdrs;
	gss_sign_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->qop_req))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->message_buffer))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_sign_res(xdrs, objp)
	XDR *xdrs;
	gss_sign_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->msg_token))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_verify_arg(xdrs, objp)
	XDR *xdrs;
	gss_verify_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->message_buffer))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->token_buffer))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_verify_res(xdrs, objp)
	XDR *xdrs;
	gss_verify_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->qop_state))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_seal_arg(xdrs, objp)
	XDR *xdrs;
	gss_seal_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->conf_req_flag))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->qop_req))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->input_message_buffer))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_seal_res(xdrs, objp)
	XDR *xdrs;
	gss_seal_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->conf_state))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->output_message_buffer))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_unseal_arg(xdrs, objp)
	XDR *xdrs;
	gss_unseal_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->gssd_context_verifier))
		return (FALSE);
	if (!xdr_GSS_CTX_ID_T(xdrs, &objp->context_handle))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->input_message_buffer))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_unseal_res(xdrs, objp)
	XDR *xdrs;
	gss_unseal_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->output_message_buffer))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->conf_state))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->qop_state))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_display_status_arg(xdrs, objp)
	XDR *xdrs;
	gss_display_status_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->status_value))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->status_type))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->mech_type))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->message_context))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_display_status_res(xdrs, objp)
	XDR *xdrs;
	gss_display_status_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->message_context))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->status_string))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}
/* gss_indicate_mechs_arg is void. This appears in the rpc call def */

bool_t
xdr_gss_indicate_mechs_res(xdrs, objp)
	XDR *xdrs;
	gss_indicate_mechs_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_OID_SET(xdrs, &objp->mech_set))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_inquire_cred_arg(xdrs, objp)
	XDR *xdrs;
	gss_inquire_cred_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_cred_verifier))
		return (FALSE);
	if (!xdr_GSS_CRED_ID_T(xdrs, &objp->cred_handle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_inquire_cred_res(xdrs, objp)
	XDR *xdrs;
	gss_inquire_cred_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->name_type))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->lifetime))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->cred_usage))
		return (FALSE);
	if (!xdr_GSS_OID_SET(xdrs, &objp->mechanisms))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_inquire_cred_by_mech_arg(xdrs, objp)
	XDR *xdrs;
	gss_inquire_cred_by_mech_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->gssd_cred_verifier))
		return (FALSE);
	if (!xdr_GSS_CRED_ID_T(xdrs, &objp->cred_handle))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->mech_type))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_inquire_cred_by_mech_res(xdrs, objp)
	XDR *xdrs;
	gss_inquire_cred_by_mech_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_OM_UINT32(xdrs, &objp->minor_status))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gsscred_name_to_unix_cred_arg(xdrs, objp)
	XDR *xdrs;
	gsscred_name_to_unix_cred_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->pname))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->name_type))
		return (FALSE);
	if (!xdr_GSS_OID(xdrs, &objp->mech_type))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gsscred_name_to_unix_cred_res(xdrs, objp)
	XDR *xdrs;
	gsscred_name_to_unix_cred_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_gid_t(xdrs, &objp->gid))
		return (FALSE);
	if (!xdr_GSSCRED_GIDS(xdrs, &objp->gids))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->major))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gsscred_expname_to_unix_cred_arg(xdrs, objp)
	XDR *xdrs;
	gsscred_expname_to_unix_cred_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_GSS_BUFFER_T(xdrs, &objp->expname))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gsscred_expname_to_unix_cred_res(xdrs, objp)
	XDR *xdrs;
	gsscred_expname_to_unix_cred_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_gid_t(xdrs, &objp->gid))
		return (FALSE);
	if (!xdr_GSSCRED_GIDS(xdrs, &objp->gids))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->major))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_get_group_info_arg(xdrs, objp)
	XDR *xdrs;
	gss_get_group_info_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_uid_t(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_uid_t(xdrs, &objp->puid))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_get_group_info_res(xdrs, objp)
	XDR *xdrs;
	gss_get_group_info_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_gid_t(xdrs, &objp->gid))
		return (FALSE);
	if (!xdr_GSSCRED_GIDS(xdrs, &objp->gids))
		return (FALSE);
	if (!xdr_OM_UINT32(xdrs, &objp->major))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_get_kmod_arg(xdrs, objp)
	XDR *xdrs;
	gss_get_kmod_arg *objp;
{

	rpc_inline_t *buf;

	if (!xdr_GSS_OID(xdrs, &objp->mech_oid))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gss_get_kmod_res(xdrs, objp)
	XDR *xdrs;
	gss_get_kmod_res *objp;
{

	rpc_inline_t *buf;

	if (!xdr_bool(xdrs, &objp->module_follow))
		return (FALSE);
	switch (objp->module_follow) {
	case TRUE:
		if (!xdr_string(xdrs, &objp->gss_get_kmod_res_u.modname, ~0))
			return (FALSE);
		break;
	case FALSE:
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}
